# Generated by Django 5.0.6 on 2024-05-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='-', max_length=15),
            preserve_default=False,
        ),
    ]
